In [1]:
import sys
sys.path.append(r'C:\Users\admin\Fusion\Fusion-0.7.0')

import numpy as np
import pandas as pd

from sklearn.metrics import make_scorer
from sklearn.metrics import roc_auc_score

from fusion.selection import CountChunker, TimeSeriesChunker
from fusion.selection import VInformationSelector
from fusion.selection import IVInformationSelector
from fusion.selection import CNSTStabilitySelector
from fusion.selection import CStabilitySelector
from fusion.selection import PSIStabilitySelector
from fusion.selection import KSStabilitySelector
from fusion.selection import GCorrelationSelector
from fusion.selection import IWrappSelector

In [2]:
df = pd.read_csv('df_for_selecting_feats.csv')

In [3]:
THRESHOLDS = {
    'VAR': 0.9,
    'IV': 0.1,
    'CONST': 0.05,
    'PSI': 0.25,
    'AVG': 0.25,
    'KS': 0.15,
    'CORR': 0.85}

In [4]:
TARGET = 'target'
KEY = 'demand'
INFORMATIVE = 'oot'
COUNTS = len([KEY, TARGET, INFORMATIVE])

### Отбор признаков

Отбор проводится по факторам информационной ценности, стабильности и корреляции.

In [5]:
chunker = CountChunker(
    count=5,
    scheme='all-next')

In [6]:
def rule(results: list, threshold: float):
    values = []
    for value in results:
        values += [value if isinstance(value, (float, np.float32)) else getattr(value, 'value')]

    return np.mean(values) < threshold

In [7]:
def types(frame: pd.DataFrame, thresholds: int):
    categorical, numerical = [], []
    for name in frame.columns:
        if frame[name].unique().size <= thresholds:
            categorical += [name]
        else:
            numerical += [name]

    return numerical, categorical

In [8]:
def typing(frame: pd.DataFrame):
    for name in frame.select_dtypes(include=['int64', 'float64']).columns:
        frame[name] = pd.to_numeric(frame[name], downcast='float')
        frame[name] = pd.to_numeric(frame[name], downcast='integer')

    return frame

In [9]:
def gini_score(y_true, y_pred):
    return 2 * roc_auc_score(y_true, y_pred) - 1

#### Селекторы

In [10]:
numerical, categorical = types(df.iloc[:, COUNTS:], 30)
len(numerical), len(categorical)

(42, 13)

In [12]:
selector = VInformationSelector(
    threshold=THRESHOLDS['VAR'],
    nan='ignore')

In [13]:
result = selector.select(df.iloc[:, COUNTS:])

In [14]:
result.report.sort_values(by='UNIQUE', ascending=False)

                                UNIQUE   PASS
FEATURES
appeal_last_lk                0.996217  False
appeal_last_em                0.995782  False
all_appeal_lk                 0.994245  False
avg_appeal_lk                 0.994245  False
all_appeal_em                 0.992145  False
avg_appeal_em                 0.992145  False
call_cnt_last                 0.971447  False
dop_ratio                     0.947661  False
dop_first_service_ratio       0.921158  False
cnt_calls_all                 0.894208   True
avg_approve                   0.805038   True
fact_order_sum_to_asked_max   0.731432   True
dop_second_service_ratio      0.698253   True
delay_ratio                   0.658327   True
extens_ratio                  0.632503   True
lifetime_start_last           0.604187   True
sum_ratio_upto5               0.570103   True
gender                        0.569726   True
fact_order_sum_to_asked_last  0.543345   True
period30_ratio                0.539021   True
sum_ratio_upto10              0.444015   True
avg_time_btw_order            0.432703   True
order_number                  0.432700   True
time_btw_last_order           0.432700   True
avg_order_sum_to_asked        0.403037   True
dops_inc_ratio                0.304892   True
dop_sum_ratio_max             0.228442   True
income                        0.222295   True
dops_inc_ratio_last           0.211525   True
cnt_session_last              0.197687   True
comis_to_paym_ratio           0.148335   True
comis_to_paym_ratio_max       0.148335   True
comis_to_paym_ratio_last      0.138806   True
dop_sum_ratio_last            0.124190   True
start_amount_inc_ratio_last   0.119502   True
avg_cnt_session               0.107575   True
avg_fact_order_sum            0.100721   True
amount_inc_ratio_last         0.090231   True
dop_sum_ratio                 0.083188   True
avg_start_amount_inc_ratio    0.082572   True
comis_to_debt_ratio           0.079252   True
comis_to_debt_ratio_max       0.079252   True
cnt_all_session               0.072778   True
avg_amount_inc_ratio          0.071095   True
comis_to_debt_ratio_last      0.069086   True
order_time_last_ratio         0.052538   True
age                           0.049427   True
lifetime_last                 0.042431   True
avg_order_time                0.032547   True
days_after_order_time         0.018398   True
ltv                           0.009022   True
ltv_last                      0.009006   True
ltv_avg                       0.009003   True
pl_last                       0.004240   True
avg_pl                        0.004166   True

In [15]:
len(selector.excluded)

9

In [16]:
selector = IVInformationSelector(
    threshold=THRESHOLDS['IV'],
    binning='quantiles',
    nan='drop',
    jobs=1)

In [17]:
%%time
result = selector.select(df.iloc[:, COUNTS:], y=df[TARGET], categories=categorical)

CPU times: total: 11.7 s
Wall time: 11.8 s

In [18]:
result.report.sort_values(by='IV', ascending=False)

,BIN 1,BIN 2,BIN 3,BIN 4,BIN 5,BIN 6,BIN 7,BIN 8,BIN 9,BIN 10,...,BIN 15,BIN 16,BIN 17,BIN 18,BIN 19,BIN 20,BIN 21,BIN 22,IV,PASS
FEATURES,,,,,,,,,,,,,,,,,,,,,
ltv,1.528553,0.684455,0.330553,-0.025995,-0.177766,-0.358841,-0.533134,-0.637418,-0.729116,-0.962229,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.529444,True
days_after_order_time,0.983467,0.850463,0.330877,0.117524,-0.087273,-0.231481,-0.290768,-0.545927,-0.921143,-1.286774,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.444238,True
period30_ratio,-1.216318,-0.821079,-0.654077,0.434463,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.373751,True
comis_to_paym_ratio,1.343414,0.325945,-0.478315,-0.469995,-0.486977,-0.444640,-0.315963,-0.224037,0.136408,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.359459,True
comis_to_paym_ratio_max,1.343403,0.325997,-0.478264,-0.469944,-0.486926,-0.444588,-0.315911,-0.223985,0.136459,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.359394,True
comis_to_paym_ratio_last,1.200440,0.629311,-0.461835,-0.444443,-0.426525,-0.362198,-0.320975,-0.290570,-0.386232,-0.191598,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.355396,True
order_number,0.347921,-0.688947,-0.901985,-1.060825,-1.423726,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.348413,True
comis_to_debt_ratio_max,1.308920,0.349515,-0.152447,-0.170443,-0.331515,-0.461256,-0.433447,-0.373034,-0.237404,-0.096843,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.302845,True
comis_to_debt_ratio,1.308920,0.349515,-0.152447,-0.170443,-0.331515,-0.461256,-0.433447,-0.373034,-0.237404,-0.096843,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.302845,True
ltv_avg,1.282607,0.506313,-0.027496,-0.208626,-0.397869,-0.384428,-0.384428,-0.365272,-0.339868,-0.142174,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.291253,True
comis_to_debt_ratio_last,1.172699,0.476329,-0.278044,-0.200994,-0.425260,-0.313536,-0.312665,-0.362631,-0.348035,-0.255873,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.269452,True
cnt_all_session,0.728426,0.571285,0.380740,0.147218,-0.024653,-0.223417,-0.354396,-0.520735,-0.646705,-0.810403,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.251204,True
dop_sum_ratio_max,1.252078,0.120787,-0.026147,-0.152772,-0.198911,-0.169608,-0.229472,-0.328794,0.000000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.227005,True
dop_sum_ratio,1.099649,-0.121471,-0.312152,-0.086714,-0.289495,-0.169747,-0.404188,-0.196934,-0.048679,0.204324,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.181983,True
dop_ratio,1.606908,-0.104744,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.166073,True
ltv_last,0.608750,0.733431,0.186285,-0.200103,-0.240902,-0.305666,-0.291666,-0.295178,-0.258157,-0.204665,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.149610,True
avg_pl,0.954140,0.194690,0.013916,-0.138159,-0.206168,-0.252063,-0.270875,-0.258641,-0.230812,-0.036321,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.139572,True
pl_last,0.896769,0.121909,0.004136,-0.200009,-0.171455,-0.229589,-0.254339,-0.214579,-0.141232,-0.013320,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.118957,True
dop_first_service_ratio,1.062594,-0.107280,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.112941,True
lifetime_start_last,0.516759,-0.034106,-0.046709,0.040505,0.035991,0.131249,0.029681,-0.028370,0.004134,0.014665,...,-0.242251,-1.627386,NaN,NaN,NaN,NaN,NaN,NaN,0.112772,True
avg_order_sum_to_asked,0.046118,-0.196725,-0.365218,-0.415341,-0.562275,0.260363,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.095210,False
dop_sum_ratio_last,0.746292,-0.293028,-0.118446,-0.150513,-0.001074,-0.298948,-0.097385,0.022397,-0.010918,0.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.091320,False
delay_ratio,-0.057812,-1.113914,0.113849,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.086889,False
avg_order_time,0.554211,0.248672,0.260215,0.090742,-0.249565,-0.285417,-0.192441,-0.321493,-0.290806,-0.035347,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.085821,False
sum_ratio_upto5,0.051296,-0.751659,0.199278,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.075103,False
avg_cnt_session,0.510456,0.033347,-0.873030,0.092248,-0.155257,-0.146048,-0.132937,-0.103827,-0.039331,0.176992,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.069206,False
lifetime_last,0.129027,0.211790,0.298446,0.286607,-0.080892,-0.246761,-0.246838,-0.180291,-0.168603,-0.189423,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.046835,False
sum_ratio_upto10,-0.085432,-0.934390,0.148147,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.046558,False
avg_fact_order_sum,0.300450,-0.189898,-0.082387,-0.064112,-0.311340,0.039433,-0.351520,-0.162812,0.051721,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.040663,False
avg_start_amount_inc_ratio,0.387682,0.188557,-0.005708,0.048511,-0.136379,-0.066864,-0.257615,-0.072437,-0.051254,-0.226376,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.032296,False
extens_ratio,0.049646,-0.586480,0.067374,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.031045,False
avg_time_btw_order,0.243562,0.163145,0.120861,0.055193,-0.044541,-0.093432,-0.132199,-0.108006,-0.147977,-0.250446,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.025041,False
dops_inc_ratio,-0.081951,-0.114417,0.161234,0.071481,0.090685,0.554358,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.023924,False
fact_order_sum_to_asked_last,-0.231466,-0.184862,-0.150997,-0.178032,0.120080,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.022827,False
start_amount_inc_ratio_last,0.178689,0.185179,0.108764,0.010626,0.128836,-0.061463,-0.145118,0.112652,-0.116936,-0.245500,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.019654,False
dops_inc_ratio_last,0.225595,-0.069492,-0.136301,-0.072941,-0.057255,-0.028065,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.018676,False
avg_amount_inc_ratio,0.230162,-0.058320,0.147709,-0.108238,-0.073314,0.097262,-0.206973,0.065306,-0.113248,-0.110387,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.018507,False
cnt_calls_all,0.043782,-0.392445,-0.442799,-0.436529,-0.507699,-0.421467,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.017641,False
order_time_last_ratio,0.080279,0.090307,0.189539,0.077475,0.150166,-0.079825,-0.124393,-0.182559,-0.160213,-0.105658,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.017038,False
avg_appeal_lk,-0.006440,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.520314,0.000000,0.000000,0.0,1.595116,NaN,NaN,NaN,0.009034,False
fact_order_sum_to_asked_max,0.231540,0.083440,-0.043204,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.008169,False
appeal_last_lk,-0.006030,1.323963,0.000000,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.007063,False
all_appeal_lk,-0.006440,0.966361,0.000000,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.005939,False
amount_inc_ratio_last,-0.052325,0.066272,0.112722,0.017665,0.056290,0.039779,-0.071780,-0.005826,-0.061843,-0.149558,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.005846,False
avg_appeal_em,-0.000568,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,-0.297868,0.0,-0.024328,0.0,1.353954,NaN,0.004391,False
call_cnt_last,-0.011159,0.296950,0.461752,0.555187,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,0.003679,False
time_btw_last_order,0.037829,0.032259,0.018024,0.032578,0.020243,0.016619,0.014944,-0.035547,-0.001722,-0.160754,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.003124,False
age,0.077546,-0.078709,-0.032696,-0.013040,0.062230,0.052081,0.038223,-0.061742,-0.053203,-0.015509,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.002925,False
cnt_session_last,-0.040541,-0.024560,0.037844,-0.000023,0.021043,0.024895,0.109821,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.002068,False
income,-0.004729,0.014546,-0.004009,-0.554877,-0.016335,0.010818,0.036657,-0.431224,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.001878,False
dop_second_service_ratio,0.056280,-0.024737,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.001392,False
appeal_last_em,-0.002567,0.536824,0.248860,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.001009,False
avg_approve,-0.077640,0.010412,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000808,False
gender,-0.017995,0.013500,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000243,False
all_appeal_em,-0.000568,0.078481,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000049,False

In [19]:
selector = CNSTStabilitySelector(
    threshold=THRESHOLDS['CONST'],
    rule=rule,
    chunker=chunker,
    jobs=5)

In [20]:
%%time
result = selector.select(df.iloc[:, COUNTS:])

CPU times: total: 188 ms
Wall time: 2.15 s

In [21]:
result.report.sort_values(by='MAX', ascending=False)

TESTS,TEST 1,TEST 2,TEST 3,TEST 4,TEST 5,TEST 6,TEST 7,TEST 8,TEST 9,TEST 10,MIN,MEAN,MAX,PASS
FEATURES,,,,,,,,,,,,,,
avg_time_btw_order,0.005693,8.750341e-02,0.012295,0.026593,9.319645e-02,0.017988,0.020899,0.075208,0.114096,0.038888,0.005693,0.049236,0.114096,True
time_btw_last_order,0.005693,8.748785e-02,0.012295,0.026593,9.318090e-02,0.017988,0.020899,0.075193,0.114080,0.038888,0.005693,0.049230,0.114080,True
comis_to_paym_ratio_last,0.000202,3.421994e-04,0.000684,0.000684,5.444113e-04,0.000887,0.000887,0.000342,0.000342,0.000000,0.000000,0.000492,0.000887,True
amount_inc_ratio_last,0.000202,2.644309e-04,0.000264,0.000264,6.221904e-05,0.000062,0.000062,0.000000,0.000000,0.000000,0.000000,0.000118,0.000264,True
income,0.000202,2.644309e-04,0.000264,0.000264,6.221904e-05,0.000062,0.000062,0.000000,0.000000,0.000000,0.000000,0.000118,0.000264,True
dops_inc_ratio_last,0.000202,2.644309e-04,0.000264,0.000264,6.221904e-05,0.000062,0.000062,0.000000,0.000000,0.000000,0.000000,0.000118,0.000264,True
start_amount_inc_ratio_last,0.000202,2.644309e-04,0.000264,0.000264,6.221904e-05,0.000062,0.000062,0.000000,0.000000,0.000000,0.000000,0.000118,0.000264,True
dops_inc_ratio,0.000109,1.555476e-04,0.000156,0.000156,4.666428e-05,0.000047,0.000047,0.000000,0.000000,0.000000,0.000000,0.000072,0.000156,True
avg_start_amount_inc_ratio,0.000109,1.555476e-04,0.000156,0.000156,4.666428e-05,0.000047,0.000047,0.000000,0.000000,0.000000,0.000000,0.000072,0.000156,True
avg_amount_inc_ratio,0.000109,1.555476e-04,0.000156,0.000156,4.666428e-05,0.000047,0.000047,0.000000,0.000000,0.000000,0.000000,0.000072,0.000156,True
comis_to_paym_ratio_max,0.000000,7.258630e-10,0.000047,0.000047,7.258630e-10,0.000047,0.000047,0.000047,0.000047,0.000000,0.000000,0.000028,0.000047,True
ltv,0.000000,7.258630e-10,0.000047,0.000047,7.258630e-10,0.000047,0.000047,0.000047,0.000047,0.000000,0.000000,0.000028,0.000047,True
lifetime_last,0.000000,0.000000e+00,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,True
sum_ratio_upto5,0.000000,0.000000e+00,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,True
sum_ratio_upto10,0.000000,0.000000e+00,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,True
lifetime_start_last,0.000000,0.000000e+00,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,True
extens_ratio,0.000000,0.000000e+00,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,True
period30_ratio,0.000000,0.000000e+00,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,True
avg_fact_order_sum,0.000000,0.000000e+00,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,True
delay_ratio,0.000000,0.000000e+00,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,True
cnt_session_last,0.000000,0.000000e+00,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,True
avg_cnt_session,0.000000,0.000000e+00,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,True
cnt_all_session,0.000000,0.000000e+00,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,True
all_appeal_lk,0.000000,0.000000e+00,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,True
avg_approve,0.000000,0.000000e+00,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,True
dop_sum_ratio,0.000000,0.000000e+00,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,True
days_after_order_time,0.000000,0.000000e+00,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,True
order_number,0.000000,0.000000e+00,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,True
ltv_last,0.000000,0.000000e+00,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,True
all_appeal_em,0.000000,0.000000e+00,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,True
avg_appeal_lk,0.000000,0.000000e+00,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,True
avg_order_sum_to_asked,0.000000,0.000000e+00,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,True
comis_to_debt_ratio_max,0.000000,0.000000e+00,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,True
comis_to_debt_ratio,0.000000,0.000000e+00,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,True
comis_to_debt_ratio_last,0.000000,0.000000e+00,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,True
comis_to_paym_ratio,0.000000,0.000000e+00,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,True
dop_second_service_ratio,0.000000,0.000000e+00,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,True
dop_first_service_ratio,0.000000,0.000000e+00,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,True
dop_ratio,0.000000,0.000000e+00,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,True
dop_sum_ratio_max,0.000000,0.000000e+00,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,True
dop_sum_ratio_last,0.000000,0.000000e+00,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,True
avg_order_time,0.000000,0.000000e+00,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,True
fact_order_sum_to_asked_max,0.000000,0.000000e+00,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,True
appeal_last_lk,0.000000,0.000000e+00,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,True
fact_order_sum_to_asked_last,0.000000,0.000000e+00,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,True
pl_last,0.000000,0.000000e+00,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,True
avg_pl,0.000000,0.000000e+00,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,True
age,0.000000,0.000000e+00,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,True
gender,0.000000,0.000000e+00,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,True
call_cnt_last,0.000000,0.000000e+00,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,True
cnt_calls_all,0.000000,0.000000e+00,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,True
appeal_last_em,0.000000,0.000000e+00,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,True
avg_appeal_em,0.000000,0.000000e+00,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,True
ltv_avg,0.000000,0.000000e+00,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,True
order_time_last_ratio,0.000000,0.000000e+00,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,True

In [22]:
len(selector.excluded)

0

In [23]:
selector.exclude(df, inplace=True)

In [24]:
selector = CStabilitySelector(
    function=lambda base, test: np.abs(np.mean(base) - np.mean(test)) / np.std(base),
    threshold=THRESHOLDS['AVG'],
    rule=rule,
    chunker=chunker,
    nan='drop',
    jobs=5)

In [25]:
%%time
result = selector.select(
    x=df[[feature for feature in df.iloc[:, COUNTS:].columns if feature in numerical]])

CPU times: total: 141 ms
Wall time: 796 ms

In [26]:
result.report.sort_values(by='MAX', ascending=False)

TESTS,TEST 1,TEST 2,TEST 3,TEST 4,TEST 5,TEST 6,TEST 7,TEST 8,TEST 9,TEST 10,MIN,MEAN,MAX,PASS
FEATURES,,,,,,,,,,,,,,
dops_inc_ratio,0.004238,0.193337,0.927936,0.914885,10.198994,48.119635,47.445967,0.055815,0.054823,0.000447,0.000447,10.791608,48.119635,False
avg_start_amount_inc_ratio,0.055240,0.121903,0.541928,0.733099,0.010887,0.079484,0.110705,0.055530,0.080804,0.012135,0.010887,0.180172,0.733099,True
income,0.067652,0.211744,0.679331,0.690688,0.135351,0.574569,0.585238,0.418271,0.428430,0.010627,0.010627,0.380190,0.690688,False
start_amount_inc_ratio_last,0.032804,0.115699,0.515661,0.456411,0.022596,0.131623,0.115472,0.071730,0.061104,0.004815,0.004815,0.152791,0.515661,True
dops_inc_ratio_last,0.021047,0.176146,0.497920,0.422938,0.056303,0.173111,0.145892,0.043910,0.033678,0.006109,0.006109,0.157705,0.497920,True
comis_to_paym_ratio_max,0.351609,0.396671,0.457695,0.417926,0.046443,0.109335,0.068349,0.050389,0.017551,0.036178,0.017551,0.195214,0.457695,True
comis_to_paym_ratio,0.351546,0.396600,0.457512,0.417749,0.046436,0.109216,0.068234,0.050301,0.017465,0.036178,0.017465,0.195124,0.457512,True
avg_pl,0.162988,0.288538,0.377502,0.448312,0.160544,0.274303,0.364849,0.145296,0.260943,0.141281,0.141281,0.262456,0.448312,False
avg_amount_inc_ratio,0.010859,0.103076,0.357255,0.434202,0.056621,0.212686,0.259931,0.039324,0.051229,0.007236,0.007236,0.153242,0.434202,True
amount_inc_ratio_last,0.009548,0.095607,0.417097,0.365232,0.048543,0.229884,0.200629,0.065742,0.055136,0.004914,0.004914,0.149233,0.417097,True
pl_last,0.147063,0.268991,0.331378,0.385129,0.156483,0.236550,0.305534,0.104786,0.195068,0.106177,0.104786,0.223716,0.385129,True
avg_time_btw_order,0.032879,0.160306,0.217228,0.310255,0.147599,0.213532,0.321285,0.090589,0.238636,0.176487,0.032879,0.190879,0.321285,True
comis_to_debt_ratio_max,0.253252,0.212510,0.293972,0.320254,0.044035,0.044010,0.072417,0.071362,0.094386,0.024633,0.024633,0.143083,0.320254,True
comis_to_debt_ratio,0.253252,0.212510,0.293972,0.320254,0.044035,0.044010,0.072417,0.071362,0.094386,0.024633,0.024633,0.143083,0.320254,True
days_after_order_time,0.013725,0.160967,0.210895,0.286736,0.170365,0.228136,0.315887,0.075799,0.190936,0.139006,0.013725,0.179245,0.315887,True
avg_order_sum_to_asked,0.075604,0.137847,0.204791,0.300898,0.059779,0.124074,0.216378,0.059924,0.145954,0.086327,0.059779,0.141158,0.300898,True
comis_to_paym_ratio_last,0.216791,0.292052,0.253203,0.215029,0.062994,0.030477,0.001474,0.031127,0.061713,0.035859,0.001474,0.120072,0.292052,True
fact_order_sum_to_asked_last,0.060138,0.118751,0.176112,0.258076,0.056997,0.112777,0.192482,0.053459,0.129848,0.075269,0.053459,0.123391,0.258076,True
fact_order_sum_to_asked_max,0.056907,0.164611,0.186112,0.243711,0.101557,0.121831,0.176143,0.018728,0.068897,0.050268,0.018728,0.118876,0.243711,True
avg_cnt_session,0.052197,0.062348,0.125021,0.239738,0.010504,0.075354,0.194054,0.054882,0.155337,0.106874,0.010504,0.107631,0.239738,True
time_btw_last_order,0.035705,0.124731,0.164719,0.234349,0.104350,0.151221,0.232836,0.064640,0.177195,0.133115,0.035705,0.142286,0.234349,True
avg_order_time,0.026664,0.124449,0.003318,0.105933,0.098411,0.023495,0.133446,0.119086,0.226493,0.119933,0.003318,0.098123,0.226493,True
avg_approve,0.048984,0.101431,0.224167,0.198050,0.055020,0.183777,0.156379,0.133930,0.105431,0.034668,0.034668,0.124183,0.224167,True
ltv,0.023274,0.133968,0.176271,0.219059,0.125055,0.172846,0.221185,0.059431,0.119542,0.072807,0.023274,0.132344,0.221185,True
extens_ratio,0.008234,0.080417,0.045405,0.145787,0.089137,0.037375,0.138306,0.117959,0.212066,0.101663,0.008234,0.097635,0.212066,True
ltv_avg,0.036133,0.024781,0.110380,0.205881,0.011826,0.077348,0.176838,0.090473,0.191413,0.111276,0.011826,0.103635,0.205881,True
cnt_all_session,0.042858,0.147357,0.148168,0.195338,0.118887,0.119809,0.173474,0.000985,0.058326,0.062444,0.000985,0.106765,0.195338,True
delay_ratio,0.041053,0.176028,0.092813,0.015664,0.130189,0.049925,0.024488,0.072431,0.139583,0.071296,0.015664,0.081347,0.176028,True
comis_to_debt_ratio_last,0.171224,0.167097,0.164004,0.171130,0.004261,0.007455,0.000098,0.002781,0.003625,0.006735,0.000098,0.069841,0.171224,True
cnt_session_last,0.044829,0.059745,0.090299,0.170556,0.015281,0.046583,0.128802,0.028029,0.101653,0.076705,0.015281,0.076248,0.170556,True
order_number,0.041559,0.152481,0.084423,0.043346,0.168833,0.109616,0.073875,0.087402,0.140154,0.051298,0.041559,0.095299,0.168833,True
order_time_last_ratio,0.010460,0.041677,0.043563,0.109643,0.032762,0.056696,0.126046,0.091602,0.162613,0.077890,0.010460,0.075295,0.162613,True
ltv_last,0.026999,0.052912,0.098359,0.158795,0.026673,0.073452,0.135661,0.050044,0.116594,0.071110,0.026673,0.081060,0.158795,True
lifetime_last,0.018114,0.048438,0.021202,0.086090,0.031941,0.041412,0.109760,0.076075,0.146958,0.076722,0.018114,0.065671,0.146958,True
period30_ratio,0.034499,0.097585,0.037915,0.062697,0.131268,0.071966,0.096595,0.062884,0.036767,0.026121,0.026121,0.065830,0.131268,True
age,0.042878,0.017640,0.050360,0.123451,0.024247,0.007188,0.077409,0.030639,0.099082,0.068364,0.007188,0.054126,0.123451,True
avg_fact_order_sum,0.021755,0.030539,0.034047,0.057553,0.008637,0.012086,0.077976,0.003382,0.084933,0.091143,0.003382,0.042205,0.091143,True
sum_ratio_upto10,0.014303,0.025304,0.023060,0.052541,0.011021,0.008773,0.066966,0.002198,0.076249,0.075360,0.002198,0.035577,0.076249,True
dop_sum_ratio_last,0.024443,0.033100,0.018969,0.011171,0.057574,0.043435,0.035632,0.013685,0.021237,0.007730,0.007730,0.026698,0.057574,True
sum_ratio_upto5,0.013091,0.020393,0.040952,0.049635,0.007328,0.027958,0.036671,0.020347,0.028941,0.008891,0.007328,0.025421,0.049635,True
dop_sum_ratio,0.008040,0.017372,0.002170,0.022055,0.025056,0.005788,0.013818,0.018815,0.037960,0.020297,0.002170,0.017137,0.037960,True
dop_sum_ratio_max,0.007597,0.030900,0.013305,0.018438,0.023150,0.005671,0.010769,0.017256,0.012223,0.005153,0.005153,0.014446,0.030900,True

In [27]:
len(selector.excluded)

3

In [28]:
selector.exclude(df, inplace=True)

In [29]:
selector = KSStabilitySelector(
    threshold=THRESHOLDS['KS'],
    rule=rule,
    chunker=chunker,
    nan='drop',
    jobs=5)

In [30]:
%%time
result = selector.select(
    x=df[[feature for feature in df.iloc[:, COUNTS:].columns if feature in numerical]])

CPU times: total: 156 ms
Wall time: 1.71 s

In [31]:
result.report.sort_values(by='MAX', ascending=False)

TESTS,TEST 1,TEST 2,TEST 3,TEST 4,TEST 5,TEST 6,TEST 7,TEST 8,TEST 9,TEST 10,MIN,MEAN,MAX,PASS
FEATURES,,,,,,,,,,,,,,
avg_amount_inc_ratio,0.016518,0.052946,0.236716,0.267391,0.042478,0.226062,0.256737,0.185882,0.209059,0.030674,0.016518,0.152446,0.267391,False
comis_to_paym_ratio_max,0.189388,0.212743,0.253463,0.215773,0.092185,0.093337,0.045152,0.040720,0.047625,0.047101,0.040720,0.123749,0.253463,True
comis_to_paym_ratio,0.189379,0.212733,0.253425,0.215735,0.092181,0.093303,0.045111,0.040692,0.047614,0.047101,0.040692,0.123727,0.253425,True
amount_inc_ratio_last,0.014789,0.058102,0.225816,0.249988,0.047656,0.215370,0.239542,0.167714,0.191887,0.024172,0.014789,0.143504,0.249988,True
avg_start_amount_inc_ratio,0.003567,0.039709,0.216180,0.208869,0.039414,0.218822,0.205494,0.184047,0.180127,0.008089,0.003567,0.130432,0.218822,True
dops_inc_ratio_last,0.039448,0.050542,0.195965,0.212049,0.029061,0.180279,0.190569,0.163312,0.164416,0.020439,0.020439,0.124608,0.212049,True
avg_cnt_session,0.040333,0.122017,0.170953,0.198205,0.084188,0.136452,0.157872,0.048936,0.076188,0.044456,0.040333,0.107960,0.198205,True
start_amount_inc_ratio_last,0.007418,0.042205,0.196708,0.189163,0.038504,0.195976,0.188432,0.171074,0.163545,0.012615,0.007418,0.120564,0.196708,True
comis_to_debt_ratio_max,0.126740,0.167000,0.193772,0.176459,0.093006,0.090627,0.062395,0.037721,0.060120,0.032977,0.032977,0.104082,0.193772,True
comis_to_debt_ratio,0.126740,0.167000,0.193772,0.176459,0.093006,0.090627,0.062395,0.037721,0.060120,0.032977,0.032977,0.104082,0.193772,True
pl_last,0.053151,0.110903,0.150878,0.189034,0.062542,0.104337,0.144438,0.043414,0.086330,0.046416,0.043414,0.099144,0.189034,True
cnt_session_last,0.041111,0.117986,0.158071,0.173673,0.077342,0.117427,0.133029,0.040085,0.055687,0.028186,0.028186,0.094260,0.173673,True
comis_to_paym_ratio_last,0.145468,0.169181,0.153341,0.142982,0.081098,0.048550,0.031006,0.032548,0.065416,0.032868,0.031006,0.090246,0.169181,True
avg_time_btw_order,0.008047,0.044766,0.077084,0.155438,0.051961,0.083083,0.162252,0.032049,0.112061,0.080818,0.008047,0.080756,0.162252,True
comis_to_debt_ratio_last,0.099208,0.145379,0.121037,0.104113,0.085773,0.045501,0.017378,0.034361,0.070029,0.029757,0.017378,0.075253,0.145379,True
days_after_order_time,0.034360,0.061114,0.095225,0.130442,0.060569,0.100965,0.140319,0.040101,0.084993,0.052374,0.034360,0.080046,0.140319,True
avg_order_sum_to_asked,0.037674,0.056982,0.084032,0.133265,0.031690,0.059300,0.104535,0.038670,0.096285,0.056029,0.031690,0.069846,0.133265,True
fact_order_sum_to_asked_last,0.029834,0.049720,0.075929,0.117508,0.022760,0.046033,0.082073,0.027377,0.065984,0.037845,0.022760,0.055506,0.117508,True
time_btw_last_order,0.022588,0.053821,0.066866,0.116237,0.032632,0.044847,0.095545,0.016831,0.067352,0.053919,0.016831,0.057064,0.116237,True
order_number,0.017608,0.087488,0.022864,0.026593,0.093181,0.036442,0.024560,0.075193,0.114080,0.038888,0.017608,0.053689,0.114080,True
avg_order_time,0.017530,0.089201,0.041711,0.043846,0.071872,0.023620,0.051235,0.053260,0.098650,0.046245,0.017530,0.053717,0.098650,True
ltv_avg,0.032914,0.071058,0.073547,0.087639,0.048005,0.047694,0.076945,0.053120,0.096752,0.045576,0.032914,0.063325,0.096752,True
cnt_all_session,0.010624,0.094811,0.089584,0.083004,0.083456,0.083827,0.075582,0.022959,0.024592,0.022975,0.010624,0.059141,0.094811,True
fact_order_sum_to_asked_max,0.020688,0.057603,0.076222,0.092772,0.038672,0.052236,0.068304,0.012771,0.047972,0.040412,0.012771,0.050765,0.092772,True
extens_ratio,0.005600,0.030803,0.023623,0.064688,0.036403,0.018723,0.059664,0.049683,0.088555,0.039339,0.005600,0.041708,0.088555,True
age,0.037860,0.046076,0.062783,0.085728,0.020520,0.027939,0.052298,0.017126,0.046945,0.033210,0.017126,0.043049,0.085728,True
ltv_last,0.048360,0.084279,0.077949,0.076891,0.043106,0.033627,0.053879,0.026770,0.049434,0.022726,0.022726,0.051702,0.084279,True
avg_approve,0.019708,0.044655,0.057723,0.084227,0.028322,0.044548,0.038590,0.035839,0.029881,0.009955,0.009955,0.039345,0.084227,True
ltv,0.037520,0.069708,0.056904,0.080984,0.044879,0.057421,0.081531,0.043056,0.049937,0.025324,0.025324,0.054726,0.081531,True
order_time_last_ratio,0.007591,0.040871,0.016684,0.037185,0.033872,0.023201,0.050703,0.048500,0.076002,0.028855,0.007591,0.036346,0.076002,True
delay_ratio,0.022166,0.065009,0.036994,0.011265,0.047851,0.018405,0.010666,0.029181,0.055002,0.025899,0.010666,0.032244,0.065009,True
period30_ratio,0.016675,0.041917,0.037252,0.044329,0.058591,0.046787,0.053864,0.026210,0.012071,0.011246,0.011246,0.034894,0.058591,True
lifetime_last,0.015617,0.049007,0.028193,0.031027,0.035677,0.013914,0.037591,0.028326,0.055905,0.029383,0.013914,0.032464,0.055905,True
dop_sum_ratio_max,0.009162,0.023989,0.020246,0.042383,0.030211,0.024586,0.043067,0.032246,0.052700,0.044674,0.009162,0.032326,0.052700,True
avg_fact_order_sum,0.011915,0.013150,0.027839,0.039831,0.007390,0.024945,0.049895,0.028217,0.050383,0.051005,0.007390,0.030457,0.051005,True
sum_ratio_upto10,0.009504,0.017179,0.009821,0.029254,0.007675,0.003274,0.037653,0.007358,0.045327,0.038514,0.003274,0.020556,0.045327,True
dop_sum_ratio_last,0.041018,0.032013,0.024042,0.034540,0.023126,0.027775,0.044339,0.009115,0.022399,0.023115,0.009115,0.028148,0.044339,True
dop_sum_ratio,0.010219,0.009944,0.016467,0.032067,0.009289,0.021382,0.033715,0.017608,0.034657,0.018059,0.009289,0.020341,0.034657,True
sum_ratio_upto5,0.010873,0.020293,0.018741,0.025398,0.013215,0.016952,0.023874,0.010002,0.031997,0.005444,0.005444,0.017679,0.031997,True

In [32]:
len(selector.excluded)

1

In [33]:
selector.exclude(df, inplace=True)

In [34]:
selector = PSIStabilitySelector(
    threshold=THRESHOLDS['PSI'],
    rule=rule,
    chunker=chunker,
    binning='quantiles',
    nan='drop',
    jobs=5)

In [35]:
%%time
result = selector.select(df.iloc[:, COUNTS:], categories=categorical)

CPU times: total: 219 ms
Wall time: 12.9 s

In [36]:
result.report.sort_values(by='MAX', ascending=False)

TESTS,TEST 1,TEST 2,TEST 3,TEST 4,TEST 5,TEST 6,TEST 7,TEST 8,TEST 9,TEST 10,MIN,MEAN,MAX,PASS
FEATURES,,,,,,,,,,,,,,
comis_to_paym_ratio_max,0.242388,0.281959,0.419835,0.340769,0.088929,7.934452e-02,0.021864,0.034294,0.049219,2.392521e-02,2.186375e-02,0.158253,0.419835,True
comis_to_paym_ratio,0.242372,0.281907,0.419733,0.340696,0.088909,7.930206e-02,0.021836,0.034311,0.049250,2.392521e-02,2.183556e-02,0.158224,0.419733,True
dops_inc_ratio_last,0.002122,0.016721,0.402844,0.332165,0.009403,3.704136e-01,0.299605,0.299356,0.239599,3.497029e-03,2.122074e-03,0.197572,0.402844,True
amount_inc_ratio_last,0.002012,0.020076,0.355403,0.398611,0.011783,3.307891e-01,0.366304,0.232400,0.248055,5.892686e-03,2.012374e-03,0.197133,0.398611,True
avg_start_amount_inc_ratio,0.000615,0.010170,0.382097,0.328012,0.009964,3.896933e-01,0.334466,0.291210,0.246880,2.263395e-03,6.146853e-04,0.199537,0.389693,True
start_amount_inc_ratio_last,0.000890,0.012493,0.309985,0.266817,0.008787,3.085201e-01,0.265182,0.242187,0.193660,2.808245e-03,8.898367e-04,0.161133,0.309985,True
pl_last,0.027119,0.110714,0.199384,0.299057,0.029789,8.302833e-02,0.156683,0.014351,0.053449,1.369645e-02,1.369645e-02,0.098727,0.299057,True
days_after_order_time,0.014585,0.059574,0.139408,0.253055,0.043436,1.350990e-01,0.285589,0.029661,0.106866,3.057391e-02,1.458537e-02,0.109785,0.285589,True
comis_to_debt_ratio_max,0.097156,0.200487,0.261579,0.225726,0.094747,6.780814e-02,0.027229,0.023654,0.061629,1.901237e-02,1.901237e-02,0.107903,0.261579,True
comis_to_debt_ratio,0.097156,0.200487,0.261579,0.225726,0.094747,6.780814e-02,0.027229,0.023654,0.061629,1.901237e-02,1.901237e-02,0.107903,0.261579,True
avg_cnt_session,0.009082,0.126758,0.209198,0.253186,0.091373,1.601484e-01,0.182892,0.008773,0.036062,1.481278e-02,8.773005e-03,0.109228,0.253186,True
comis_to_paym_ratio_last,0.120163,0.237614,0.241183,0.084101,0.051305,2.122460e-02,0.012330,0.009354,0.023970,7.920879e-03,7.920879e-03,0.080917,0.241183,True
avg_time_btw_order,0.001122,0.027219,0.052502,0.174293,0.023944,5.175165e-02,0.176006,0.007994,0.076465,3.994754e-02,1.122341e-03,0.063125,0.176006,True
comis_to_debt_ratio_last,0.062076,0.142173,0.108006,0.075095,0.052022,2.446721e-02,0.004835,0.040410,0.030419,8.438469e-03,4.835337e-03,0.054794,0.142173,True
ltv,0.024585,0.063352,0.093058,0.122057,0.027970,4.453942e-02,0.087809,0.028862,0.061432,8.329015e-03,8.329015e-03,0.056199,0.122057,True
ltv_last,0.023975,0.115992,0.098580,0.082347,0.043179,2.888758e-02,0.028477,0.013761,0.031881,8.112433e-03,8.112433e-03,0.047519,0.115992,True
ltv_avg,0.005342,0.072878,0.069201,0.111832,0.059577,5.356898e-02,0.059607,0.027564,0.077671,1.353917e-02,5.341929e-03,0.055078,0.111832,True
cnt_session_last,0.008146,0.055478,0.087884,0.106080,0.022466,4.403695e-02,0.055495,0.003909,0.013260,6.267077e-03,3.909303e-03,0.040302,0.106080,True
dop_first_service_ratio,0.040535,0.032557,0.037807,0.097531,0.000424,4.610115e-05,0.011816,0.000191,0.016737,1.334291e-02,4.610115e-05,0.025099,0.097531,True
cnt_all_session,0.001592,0.075131,0.083799,0.094946,0.058800,6.697757e-02,0.075369,0.006307,0.014892,6.999002e-03,1.591527e-03,0.048481,0.094946,True
avg_order_sum_to_asked,0.006364,0.023744,0.038002,0.090462,0.015001,2.089995e-02,0.051506,0.007893,0.042474,1.288245e-02,6.363792e-03,0.030923,0.090462,True
dop_ratio,0.049889,0.031743,0.018000,0.083929,0.001944,7.640654e-03,0.004117,0.001870,0.011744,2.308242e-02,1.869844e-03,0.023396,0.083929,True
time_btw_last_order,0.003238,0.018821,0.025232,0.082811,0.009697,1.632273e-02,0.065766,0.003522,0.033579,1.809124e-02,3.238496e-03,0.027708,0.082811,True
cnt_calls_all,0.073459,0.041906,0.027532,0.015092,0.005059,1.225232e-02,0.026934,0.001819,0.009608,3.113688e-03,1.819333e-03,0.021677,0.073459,True
avg_order_time,0.001980,0.040187,0.012536,0.021906,0.026531,6.874809e-03,0.022668,0.019832,0.065978,1.498917e-02,1.980388e-03,0.023348,0.065978,True
fact_order_sum_to_asked_last,0.004053,0.016366,0.030333,0.062045,0.004818,1.179341e-02,0.031081,0.004237,0.018052,6.408662e-03,4.052658e-03,0.018919,0.062045,True
fact_order_sum_to_asked_max,0.003102,0.024979,0.034092,0.058821,0.010135,2.296783e-02,0.034705,0.003016,0.014637,7.009724e-03,3.016036e-03,0.021347,0.058821,True
extens_ratio,0.000145,0.006170,0.003130,0.027273,0.007941,1.933934e-03,0.023401,0.016352,0.058123,1.262112e-02,1.452355e-04,0.015709,0.058123,True
age,0.010788,0.022039,0.033946,0.057940,0.004864,8.953481e-03,0.019325,0.002366,0.013128,6.089118e-03,2.365611e-03,0.017944,0.057940,True
lifetime_start_last,0.004799,0.007846,0.037609,0.050276,0.001512,1.773999e-02,0.027466,0.012782,0.020933,1.684255e-03,1.511691e-03,0.018265,0.050276,True
avg_approve,0.002523,0.013532,0.050226,0.048167,0.006814,3.047117e-02,0.020153,0.019386,0.011385,1.144506e-03,1.144506e-03,0.020380,0.050226,True
order_time_last_ratio,0.001490,0.010061,0.007654,0.018485,0.007538,7.655206e-03,0.022731,0.013222,0.035835,7.521505e-03,1.490109e-03,0.013219,0.035835,True
dop_sum_ratio_max,0.010165,0.007070,0.001594,0.029823,0.010557,1.813566e-02,0.035292,0.010156,0.032780,3.085852e-02,1.593993e-03,0.018643,0.035292,True
avg_fact_order_sum,0.001055,0.001583,0.005895,0.025913,0.001363,6.620148e-03,0.030816,0.007036,0.035117,2.214495e-02,1.054775e-03,0.013754,0.035117,True
order_number,0.001747,0.019280,0.006338,0.005612,0.031246,1.162356e-02,0.008837,0.009242,0.018827,1.715152e-03,1.715152e-03,0.011447,0.031246,True
lifetime_last,0.002588,0.011597,0.007371,0.019402,0.006352,5.284688e-03,0.018207,0.009004,0.030113,7.622795e-03,2.588211e-03,0.011754,0.030113,True
period30_ratio,0.001361,0.014598,0.015430,0.021159,0.022333,2.004510e-02,0.028352,0.004221,0.011125,1.446015e-03,1.360770e-03,0.014007,0.028352,True
dop_sum_ratio_last,0.021707,0.015853,0.009658,0.025509,0.004041,7.087557e-03,0.011993,0.002963,0.013309,1.240334e-02,2.962727e-03,0.012452,0.025509,True
delay_ratio,0.002398,0.024703,0.008160,0.000751,0.014429,3.082325e-03,0.001095,0.004834,0.016571,3.734960e-03,7.514606e-04,0.007976,0.024703,True
dop_sum_ratio,0.001906,0.003812,0.003793,0.020670,0.002612,4.993604e-03,0.021525,0.009052,0.024136,1.671439e-02,1.905988e-03,0.010921,0.024136,True
call_cnt_last,0.022972,0.018871,0.012060,0.004853,0.000270,1.698861e-03,0.006863,0.000792,0.004781,1.731596e-03,2.698860e-04,0.007489,0.022972,True
dop_second_service_ratio,0.003900,0.019636,0.017765,0.001514,0.006032,5.016471e-03,0.000554,0.000047,0.010242,8.904479e-03,4.677823e-05,0.007361,0.019636,True
gender,0.000253,0.000319,0.003700,0.011991,0.001140,2.017460e-03,0.008760,0.006192,0.016223,2.369769e-03,2.530546e-04,0.005297,0.016223,True
sum_ratio_upto5,0.000468,0.002892,0.002228,0.004310,0.001340,2.441711e-03,0.004840,0.005117,0.013586,3.832837e-04,3.832837e-04,0.003761,0.013586,True
all_appeal_em,0.000670,0.003880,0.007951,0.005462,0.001312,3.940678e-03,0.002277,0.000691,0.000130,2.204638e-04,1.302233e-04,0.002653,0.007951,True
sum_ratio_upto10,0.000223,0.001516,0.000549,0.004303,0.001747,9.664754e-05,0.004727,0.001598,0.005610,7.146137e-03,9.664754e-05,0.002752,0.007146,True
avg_appeal_em,0.001230,0.002135,0.004063,0.003756,0.000136,8.590422e-04,0.000837,0.000324,0.000383,2.538282e-04,1.364687e-04,0.001398,0.004063,True
all_appeal_lk,0.002366,0.002711,0.003165,0.003139,0.000011,5.638824e-05,0.000053,0.000017,0.000015,5.648087e-08,5.648087e-08,0.001153,0.003165,True
avg_appeal_lk,0.002371,0.002604,0.002514,0.003018,0.000008,8.284855e-06,0.000114,0.000002,0.000129,1.534953e-04,1.540433e-06,0.001092,0.003018,True
appeal_last_em,0.000657,0.001629,0.002702,0.002487,0.000214,6.781444e-04,0.000575,0.000133,0.000089,4.308304e-06,4.308304e-06,0.000917,0.002702,True
appeal_last_lk,0.001677,0.002029,0.001654,0.002400,0.000016,8.352226e-08,0.000062,0.000019,0.000015,6.692217e-05,8.352226e-08,0.000794,0.002400,True

In [37]:
len(selector.excluded)

0

In [38]:
selector.exclude(df, inplace=True)

In [39]:
selector = GCorrelationSelector(
    threshold=THRESHOLDS['CORR'],
    method='pearson',
    nan='drop')

In [40]:
%%time
result = selector.select(df.iloc[:, COUNTS:])

CPU times: total: 1.06 s
Wall time: 1.06 s

In [41]:
result.report

FEATURES,ltv_last,ltv_avg,comis_to_debt_ratio_max,comis_to_debt_ratio,comis_to_debt_ratio_last,comis_to_paym_ratio_max,comis_to_paym_ratio,comis_to_paym_ratio_last,dop_second_service_ratio,dop_first_service_ratio,...,dop_sum_ratio,ltv,days_after_order_time,order_number,delay_ratio,avg_fact_order_sum,time_btw_last_order,lifetime_start_last,lifetime_last,order_time_last_ratio
FEATURES,,,,,,,,,,,,,,,,,,,,,
ltv_last,1.000000,0.852684,0.285689,0.285689,0.319078,0.128389,0.128525,0.072961,0.089202,0.094559,...,-0.214602,0.517245,0.277139,-0.013999,-0.326343,0.388250,-0.038930,0.213228,0.686901,0.629185
ltv_avg,0.852684,1.000000,0.353162,0.353162,0.318803,0.157801,0.157960,0.114183,0.091695,0.118479,...,-0.232106,0.589716,0.338641,-0.014264,-0.439727,0.423146,-0.019919,0.212139,0.606251,0.566463
comis_to_debt_ratio_max,0.285689,0.353162,1.000000,1.000000,0.876436,0.830413,0.830424,0.659258,0.173391,0.232945,...,0.502675,0.170574,0.252235,-0.003428,-0.383570,-0.378694,0.016886,0.107987,0.432427,0.421682
comis_to_debt_ratio,0.285689,0.353162,1.000000,1.000000,0.876436,0.830413,0.830424,0.659258,0.173391,0.232945,...,0.502675,0.170574,0.252235,-0.003428,-0.383570,-0.378694,0.016886,0.107987,0.432427,0.421682
comis_to_debt_ratio_last,0.319078,0.318803,0.876436,0.876436,1.000000,0.737979,0.737996,0.744527,0.145128,0.201929,...,0.442405,0.190125,0.268194,0.040869,-0.334121,-0.339283,0.017506,0.109705,0.476556,0.457867
comis_to_paym_ratio_max,0.128389,0.157801,0.830413,0.830413,0.737979,1.000000,1.000000,0.821987,0.096188,0.314554,...,0.403261,0.146294,0.203277,0.130792,-0.104904,-0.333927,-0.005513,0.091276,0.175689,0.164659
comis_to_paym_ratio,0.128525,0.157960,0.830424,0.830424,0.737996,1.000000,1.000000,0.821987,0.096157,0.314535,...,0.403247,0.146294,0.203105,0.130820,-0.104743,-0.333930,-0.005513,0.091275,0.174908,0.163751
comis_to_paym_ratio_last,0.072961,0.114183,0.659258,0.659258,0.744527,0.821987,0.821987,1.000000,0.031242,0.259649,...,0.321262,0.159408,0.215602,0.181149,-0.063059,-0.278601,0.001250,0.079792,0.123051,0.111979
dop_second_service_ratio,0.089202,0.091695,0.173391,0.173391,0.145128,0.096188,0.096157,0.031242,1.000000,0.295173,...,0.432664,-0.293897,-0.279385,-0.464146,-0.110231,-0.087244,0.124364,-0.069204,0.043490,0.056338
dop_first_service_ratio,0.094559,0.118479,0.232945,0.232945,0.201929,0.314554,0.314535,0.259649,0.295173,1.000000,...,0.224369,0.088151,0.053014,0.040660,-0.005949,0.033889,0.015933,0.050709,0.020644,0.012182
dop_ratio,0.116594,0.145833,0.284026,0.284026,0.255094,0.392976,0.392955,0.335007,0.357497,0.803297,...,0.253688,0.137250,0.102308,0.085097,0.002671,0.048465,0.021716,0.070929,0.026630,0.014202
dop_sum_ratio_max,-0.204071,-0.207185,0.481617,0.481617,0.479978,0.448526,0.448529,0.416588,0.181049,0.208080,...,0.781224,-0.045917,0.190924,0.149524,-0.068860,-0.663401,0.039606,0.021442,0.006926,0.003984
dop_sum_ratio_last,-0.207802,-0.170159,0.409633,0.409633,0.465036,0.308696,0.308685,0.311191,0.442691,0.167314,...,0.825720,-0.260815,-0.112785,-0.221308,-0.136677,-0.569022,0.099896,-0.107574,-0.001440,0.020683
avg_order_time,0.582651,0.706483,0.532873,0.532873,0.474860,0.212447,0.211302,0.149368,0.064948,0.018240,...,0.022662,0.342410,0.387909,-0.087591,-0.650860,0.027543,-0.002856,0.188419,0.856010,0.830823
avg_time_btw_order,-0.053780,-0.038111,0.006032,0.006032,0.000717,-0.001222,-0.001222,-0.000398,0.097693,0.014329,...,0.081857,-0.078470,0.539714,-0.081164,-0.018064,-0.051011,0.865627,-0.093165,-0.047613,-0.034647
avg_order_sum_to_asked,0.049435,0.040330,-0.173425,-0.173425,-0.162574,-0.110562,-0.110569,-0.106152,-0.024955,-0.042592,...,-0.225286,0.017268,-0.037797,-0.004117,0.160450,0.253344,0.044846,-0.193852,-0.070414,-0.037032
fact_order_sum_to_asked_max,0.061864,0.064369,-0.127306,-0.127306,-0.084144,-0.037344,-0.037338,-0.001458,-0.127825,-0.020100,...,-0.264105,0.190758,0.163613,0.204050,0.166849,0.232374,0.017895,-0.075661,-0.045279,-0.035548
fact_order_sum_to_asked_last,0.070059,0.018675,-0.157115,-0.157115,-0.193795,-0.100971,-0.100980,-0.144040,-0.003534,-0.033870,...,-0.186861,-0.021069,-0.061728,-0.027044,0.156618,0.224304,0.043732,-0.213031,-0.067349,-0.030358
pl_last,0.293090,0.226595,0.401161,0.401161,0.489658,0.322199,0.322272,0.313671,0.048207,0.117697,...,0.248283,0.260840,0.209964,0.189362,-0.176640,-0.173542,-0.110978,0.079458,0.330999,0.315351
age,0.119623,0.139038,-0.069376,-0.069376,-0.066961,-0.069640,-0.069671,-0.058690,-0.042004,0.006675,...,-0.184267,0.126676,0.065902,0.028382,0.045089,0.225388,0.023604,0.024228,0.035365,0.029274
gender,-0.076925,-0.090508,-0.015072,-0.015072,-0.016188,0.004868,0.004869,0.003828,-0.025994,0.006215,...,0.043004,-0.042890,-0.032675,0.041765,0.001637,-0.066843,-0.034017,-0.018234,-0.054489,-0.049980
call_cnt_last,0.134191,0.121276,0.031904,0.031904,0.029810,-0.018396,-0.018387,-0.027483,0.005122,-0.018381,...,-0.025248,0.041224,0.027495,-0.032016,-0.086817,0.031849,-0.002680,0.017853,0.142237,0.136473
cnt_calls_all,0.086546,0.106013,0.019128,0.019128,0.025482,0.005011,0.005027,0.018240,-0.102807,-0.001705,...,-0.069408,0.215279,0.212619,0.173928,-0.028205,0.059034,0.000612,0.069721,0.078670,0.062915
appeal_last_em,0.017301,0.012169,0.010859,0.010859,0.010300,0.006042,0.006045,0.001385,0.000856,-0.002004,...,0.003376,-0.001947,-0.003445,-0.010206,-0.020394,-0.003417,-0.005500,0.004516,0.026296,0.026354
avg_appeal_em,0.017201,0.018757,0.013575,0.013575,0.011324,0.006764,0.006767,0.002487,-0.000481,-0.005809,...,0.002340,-0.002248,0.001897,-0.016029,-0.029351,-0.003518,0.010949,0.000504,0.027673,0.029323
all_appeal_em,0.021553,0.020414,0.013757,0.013757,0.015865,0.014454,0.014458,0.013075,-0.024851,-0.002018,...,-0.008934,0.040888,0.046855,0.032384,-0.016105,0.003729,0.006491,0.016889,0.027947,0.024816
appeal_last_lk,0.007847,0.005789,-0.001184,-0.001184,-0.004884,0.015963,0.015966,0.009366,0.008418,-0.003272,...,0.001756,-0.017630,-0.021780,-0.025835,-0.009658,0.003248,0.001831,-0.014540,0.005737,0.008936
avg_appeal_lk,0.004933,0.006153,-0.001912,-0.001912,-0.006417,0.016633,0.016636,0.008958,0.009684,-0.005219,...,0.001155,-0.019840,-0.023888,-0.028995,-0.010457,0.003371,0.003318,-0.015295,0.002995,0.006286
all_appeal_lk,0.011025,0.009779,-0.000391,-0.000391,-0.002251,0.020362,0.020365,0.015655,-0.001745,-0.003521,...,-0.005237,-0.001044,-0.003871,-0.010201,-0.005305,0.007495,0.001597,-0.005040,0.005246,0.005866
start_amount_inc_ratio_last,0.000404,-0.001445,-0.009594,-0.009594,-0.006820,-0.011100,-0.011098,-0.007217,-0.012546,-0.019507,...,-0.009460,0.000649,0.001389,0.004500,0.000783,0.007795,0.000718,0.011097,-0.000915,-0.002787
avg_start_amount_inc_ratio,-0.000334,-0.002023,-0.009346,-0.009346,-0.006420,-0.011515,-0.011513,-0.007556,-0.011838,-0.025126,...,-0.008326,-0.002463,-0.003523,-0.000437,-0.001367,0.003585,-0.003812,0.009233,-0.000069,-0.001752
amount_inc_ratio_last,0.002788,-0.000781,-0.011876,-0.011876,-0.010715,-0.012082,-0.012079,-0.010176,-0.012730,-0.020271,...,-0.013272,0.001349,0.001623,0.005437,0.003179,0.013904,0.000879,0.009828,-0.000973,-0.002737
sum_ratio_upto5,-0.285177,-0.299921,0.368525,0.368525,0.347309,0.293334,0.293341,0.264672,0.033422,-0.039133,...,0.739479,-0.229950,-0.026538,-0.045462,-0.069055,-0.684245,0.051223,-0.102146,-0.032381,-0.011869
sum_ratio_upto10,-0.341540,-0.368672,0.354952,0.354952,0.315723,0.320944,0.320979,0.265221,0.060313,-0.037618,...,0.636385,-0.305711,-0.061174,-0.067782,-0.071287,-0.855303,0.047421,-0.107199,-0.053194,-0.032542
extens_ratio,0.531975,0.638362,0.473774,0.473774,0.413366,0.232294,0.232317,0.163671,0.053867,0.017252,...,-0.003156,0.315553,0.281027,-0.080404,-0.482332,0.058246,0.010594,0.103734,0.596695,0.595703
period30_ratio,-0.111801,-0.149908,-0.117673,-0.117673,-0.167512,-0.186184,-0.186222,-0.235490,0.333279,-0.059541,...,0.150861,-0.633648,-0.725992,-0.675576,-0.043949,-0.093124,-0.156421,-0.252397,-0.080556,-0.025551
dops_inc_ratio_last,-0.000877,-0.002342,0.002725,0.002725,0.006250,0.001780,0.001781,0.004285,0.006859,-0.004808,...,0.008596,-0.003421,0.000091,-0.001648,0.000299,-0.005286,0.003258,0.005661,-0.000269,-0.001505
cnt_session_last,0.492175,0.406977,0.270312,0.270312,0.299004,0.123857,0.123844,0.082544,0.049897,0.011667,...,-0.036088,0.173168,0.126730,-0.071484,-0.234411,0.080317,-0.033432,0.111875,0.517387,0.490005
avg_cnt_session,0.392155,0.455808,0.315080,0.315080,0.274038,0.144935,0.144918,0.093938,0.053529,0.013736,...,-0.033579,0.189692,0.149151,-0.079081,-0.289568,0.079316,-0.022949,0.112274,0.431541,0.416110
cnt_all_session,0.225461,0.250161,0.162852,0.162852,0.181725,0.162874,0.162889,0.176936,-0.307696,0.039779,...,-0.162544,0.633593,0.569156,0.637847,-0.022024,0.117374,-0.092226,0.222969,0.212635,0.166897
avg_approve,0.045941,0.049206,-0.055757,-0.055757,-0.047271,-0.043749,-0.043771,-0.037771,0.017178,0.018134,...,-0.100966,0.014839,-0.019798,-0.008991,0.043531,0.125988,-0.005050,-0.022276,0.004334,0.005786
dop_sum_ratio,-0.214602,-0.232106,0.502675,0.502675,0.442405,0.403261,0.403247,0.321262,0.432664,0.224369,...,1.000000,-0.297695,-0.120229,-0.200807,-0.117936,-0.689472,0.091809,-0.104973,-0.003838,0.019084
ltv,0.517245,0.589716,0.170574,0.170574,0.190125,0.146294,0.146294,0.159408,-0.293897,0.088151,...,-0.297695,1.000000,0.708798,0.628451,-0.097183,0.375636,-0.099641,0.274309,0.333508,0.269309
days_after_order_time,0.277139,0.338641,0.252235,0.252235,0.268194,0.203277,0.203105,0.215602,-0.279385,0.053014,...,-0.120229,0.708798,1.000000,0.577022,-0.151311,0.078558,0.392283,0.233259,0.364833,0.310576
order_number,-0.013999,-0.014264,-0.003428,-0.003428,0.040869,0.130792,0.130820,0.181149,-0.464146,0.040660,...,-0.200807,0.628451,0.577022,1.000000,0.154581,0.097765,-0.125458,0.191051,-0.044848,-0.077691
delay_ratio,-0.326343,-0.439727,-0.383570,-0.383570,-0.334121,-0.104904,-0.104743,-0.063059,-0.110231,-0.005949,...,-0.117936,-0.097183,-0.151311,0.154581,1.000000,0.090612,-0.042808,-0.048431,-0.511834,-0.524236
avg_fact_order_sum,0.388250,0.423146,-0.378694,-0.378694,-0.339283,-0.333927,-0.333930,-0.278601,-0.087244,0.033889,...,-0.689472,0.375636,0.078558,0.097765,0.090612,1.000000,-0.050836,0.136756,0.051302,0.024038
time_btw_last_order,-0.038930,-0.019919,0.016886,0.016886,0.017506,-0.005513,-0.005513,0.001250,0.124364,0.015933,...,0.091809,-0.099641,0.392283,-0.125458,-0.042808,-0.050836,1.000000,-0.087915,-0.029731,-0.017466
lifetime_start_last,0.213228,0.212139,0.107987,0.107987,0.109705,0.091276,0.091275,0.079792,-0.069204,0.050709,...,-0.104973,0.274309,0.233259,0.191051,-0.048431,0.136756,-0.087915,1.000000,0.196360,0.002467
lifetime_last,0.686901,0.606251,0.432427,0.432427,0.476556,0.175689,0.174908,0.123051,0.043490,0.020644,...,-0.003838,0.333508,0.364833,-0.044848,-0.511834,0.051302,-0.029731,0.196360,1.000000,0.946086
order_time_last_ratio,0.629185,0.566463,0.421682,0.421682,0.457867,0.164659,0.163751,0.111979,0.056338,0.012182,...,0.019084,0.269309,0.310576,-0.077691,-0.524236,0.024038,-0.017466,0.002467,0.946086,1.000000

In [42]:
len(selector.excluded)

11

In [43]:
selector.exclude(df, inplace=True)

In [44]:
df

,demand,target,oot,ltv_avg,comis_to_debt_ratio_last,comis_to_paym_ratio,comis_to_paym_ratio_last,dop_second_service_ratio,dop_first_service_ratio,dop_ratio,...,avg_approve,dop_sum_ratio,ltv,days_after_order_time,order_number,delay_ratio,avg_fact_order_sum,time_btw_last_order,lifetime_start_last,order_time_last_ratio
0,23809874,1,0,8144.91,0.29,0.09,0.09,1.0,1.0,1.0,...,1.0,0.600,8144.914,69,1,0.0,4000.000,NaN,22,3.181818
1,23810121,1,0,4923.76,0.16,0.10,0.10,1.0,1.0,1.0,...,1.0,0.300,4923.763,16,1,1.0,8000.000,NaN,16,1.062500
2,23845577,0,0,3257.54,0.29,0.14,0.14,1.0,1.0,1.0,...,1.0,0.800,3257.543,5,1,1.0,3000.000,NaN,16,0.375000
3,24846191,0,0,4387.87,0.16,0.11,0.09,1.0,1.0,1.0,...,1.0,0.436,8775.745,53,2,1.0,5500.000,25.0,26,0.923077
4,30554758,1,0,4193.63,0.20,0.11,0.11,1.0,1.0,1.0,...,1.0,0.450,12580.888,211,3,1.0,5333.333,150.0,16,0.562500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
321437,46765176,0,0,3193.60,0.08,0.06,0.06,1.0,1.0,1.0,...,1.0,0.240,3193.600,7,1,1.0,10000.000,NaN,30,0.233333
321438,48222616,0,0,3653.12,0.13,0.08,0.09,1.0,1.0,1.0,...,1.0,0.240,7306.243,38,2,1.0,10000.000,26.0,21,0.238095
321439,49464215,0,0,3693.07,0.13,0.08,0.09,1.0,1.0,1.0,...,1.0,0.240,11079.205,62,3,1.0,10000.000,24.0,19,0.000000
321440,49512219,0,0,3734.27,0.13,0.09,0.09,1.0,1.0,1.0,...,1.0,0.240,14937.088,65,4,1.0,10000.000,1.0,18,0.111111
321441,49819448,1,0,3338.64,0.12,0.09,0.10,0.0,1.0,1.0,...,1.0,0.202,16693.200,70,5,1.0,10000.000,5.0,16,0.000000

In [45]:
df.to_csv('df_for_analyzing_feats.csv', index=False)